### ISSUE TITLE
Sample code and doc for offline user data

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk-samples#10]
via carto and direct

**Comment by jaakla** [comment]
Sample data: CARTO offline package polygons as vector tiles: 
[offline-packages.mbtiles.zip](https://github.com/CartoDB/mobile-sdk-samples/files/1246137/offline-packages.mbtiles.zip)
Usage sample with style, carto-fonts.zip is same as in carto samples.

```java
        String cartoCss =
                "#offlinepackages {\n" +
                "  polygon-fill: #374C70;\n" +
                "  polygon-opacity: 0.9;\n" +
                "  polygon-gamma: 0.5;\n" +
                        " ::outline {" +
                        " line-color: #FFF;\n" +
                        "}" +
                "#offlinepackages::labels {\n" +
                "  text-name: [package_id];\n" +
                "  text-face-name: 'DejaVu Sans Book';\n" +
                "  text-size: 10;\n" +
                "  text-fill: #130505;\n" +
                "  text-label-position-tolerance: 0;\n" +
                "  text-halo-radius: 1;\n" +
                "  text-halo-fill: #dee3e7;\n" +
                "  text-dy: -10;\n" +
                "  text-allow-overlap: false;\n" +
                "  text-placement: nutibillboard;\n" +
                "  text-placement-type: dummy;\n" +
                "}"+
                "}";

        BinaryData styleAsset = AssetUtils.loadAsset("carto-fonts.zip");
        ZippedAssetPackage assetPackage = new ZippedAssetPackage(styleAsset);

        MBVectorTileDecoder decoder = new MBVectorTileDecoder(new CartoCSSStyleSet(cartoCss, assetPackage));

        MBTilesTileDataSource mbDataSource = createMbtilesDataSourceFromAsset("offline-packages.mbtiles");
        VectorTileLayer mbLayer = new VectorTileLayer(mbDataSource,decoder);
       mapView.getLayers().add(mbLayer);

```

**Comment by jaakla** [comment]
Sample data creation procedure:
1. Get geojson - from GIS or save from CARTO
2. Fix it - add ID values. CARTO exports (https://github.com/CartoDB/cartodb/issues/12639) and many other sources do not have this. This is needed to avoid duplicate texts on map. I used https://github.com/mapbox/geojson-quirks tool to fix it with `--add-id-from-property cartodb_id` command
3. convert to vectortiles, make sure layer name is correct. I used MB tippecanoe: `tippecanoe -lofflinepackages -o offline-packages.mbtiles --maximum-zoom=6 offline-packages.geojson`
4. create suitable CartoCSS, make sure that layername is same as in vector tiles data (set with -l parameter in tippecanoe).
5. in code make sure to add fonts asset if texts are rendered, see sample code. Here you can find suitable [carto-fonts.zip file](https://github.com/CartoDB/mobile-ios-samples/blob/master/Assets/carto-fonts.zip) with all fonts supported by Builder

**Comment by Nikituh** [comment]
* Droid: https://github.com/CartoDB/mobile-dotnet-samples/blob/dev/AdvancedMap.Droid/Sections/Other/BundledUserDataActivity.cs
* iOS: https://github.com/CartoDB/mobile-dotnet-samples/blob/dev/AdvancedMap.iOS/Sections/Other/BundledUserDataController.cs
