### ISSUE TITLE
Update samples v2

### ISSUE THREAD

**Issue by Nikituh** [CartoDB/mobile-sdk-samples#12]
#### General
- [x] Travis - Check if I could easily make it run
- [x] Cleanup Assets - world_zoom, tesla, old styles etc.
- [x] Subtitle shown as both title and subtitle in map view
   
**BaseMaps**
- [x] Base Maps -> Online Base Maps
- [x] HERE raster - add "here.satellite.day@2x" , "here.normal.day@2x"

**Offline Maps**
- [x] ~~Import world seed (world_zoom5.mbtiles); @jaakla Create file~~ Showing a map when none is downloaded can seem confusing, added a banner to guide the user to download
- [x] custom_region -> custom region

**Online Routing**
- [x] Description  "Online routing using Mapzen service"
- [x] Instruction: "Long-click 2 locations on map to set route start and destination"
- [x]  service.setProfile("auto"); // other costing models: pedestrian etc, cf. https://github.com/valhalla/valhalla-docs/blob/master/api-reference.md
- [x] Instruction click: show details as popup

**Offline Routing**
- [x] Instruction: "Long-click..." (as online)
- [x] Instruction click: show details as popup

**Online Reverse Geocoding**
- [x] Name: Online Rev-Geocode
- [x] Instruction  "Click on map to show address (Reverse Geocoding data)"
- [x] ~~Show geometry (line, polygon)~~ it's an SDK feature, works with offline packages, but not with Pelias

**Online Geocoding**
- [x] Description: "Geocoding / address autocomplete with Mapzen Pelias geocoder"

**Offline Reverse**
- [x] cf online reverse
- [x] Instruction: "Click Globe button to download data and then click on map", või lühem kui download on tehtud

**Offline Geocoding**
- [x] Description: "Geocoding / address autocomplete Offline OSM"

**WMS**
- [x] ~~New source @jaakla~~ Will, instead, modify exising sample to improve load time

**Clustering**
- [x] Toast "Loading markers..."

**Comment by jaakla** [comment]
World carto.streets map for up to zoom 5 is here: https://drive.google.com/file/d/0B3Rm1qU6KnySdFNKc1BDTDU2dXM/view?usp=sharing . It is bigger but should have a bit more details also.
