### ISSUE TITLE
Offline routing sample for 4.1.0 SDK

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk-samples#2]
Upgrade offline routing samples to use SDK 4.1.0 rewritten offline routing.
* Probably minor changes in app side
* Two package download modes: for bounding box and country, like with offline maps
* Put initially into separate "development" branch.
* Bigger preparation in SDK (to download packages)
* Coordination with server/data preparation

**Comment by jaakla** [comment]
Requires working sdk dev build with valhalla routing

**Comment by jaakla** [comment]
start with Android, using 4.1.0-snapshot build of SDK

**Comment by jaakla** [comment]
Data from https://github.com/CartoDB/mobile-tileserver/issues/36

**Comment by Nikituh** [comment]
Working on iOS **dev branch**, Android (**dev branch**) produces the following error:
`Exception while translating route: _Map_base::at`

**Comment by jaakla** [comment]
@mtehver to check Android issue

**Comment by Nikituh** [comment]
Completed some time ago, closing
