### ISSUE TITLE
Update samples to 4.1.0-rc.1

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk-samples#7]
Review that all samples in all platforms and languages (java, hellomap etc) in dev branches are updated and tested with 4.1.0-rc.1 version. Minimal changes are datasource to carto.streets and style change to Voyager for basemap.

Do not merge to master yet, this comes with final release.

**Comment by Nikituh** [comment]
Done:
* Droid: https://github.com/CartoDB/mobile-android-samples/tree/AdvancedMapKotlin
* iOS: https://github.com/CartoDB/mobile-ios-samples/tree/dev
* .NET: https://github.com/CartoDB/mobile-dotnet-samples/tree/dev
