### ISSUE TITLE
Add offline search sample

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk-samples#8]
I think 3 languages would be enough: swift,kotlin,c#. For exact data/features suggestions are welcome. One example "find gas stations near route from vector tiles (which are already downloaded)" - as extra feature to offline routing. Or download geojson data from CARTO SQL API public table for similar case.

**Comment by mtehver** [comment]
I added a basic Kotlin sample (AdvancedMapKotlin branch) - it allows to specify route via endpoints and the sample finds 'attractions' within 500m radius of the route.
