### ISSUE TITLE
data collection sample app

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-sdk-samples#9]
Point data collection app, close to reallife case. 

1.Collects:

* location: from GPS + user-adjusted 
* photo from camera (upload to s3 bucket, write url).
* Simple form: description
* automatic field - collection time

2. Insert to CARTO database, show locally added points

Extra features:

* Cache offline until user gets online? With manual button ok.
* Allow pre-download offline base map

**Comment by Nikituh** [comment]
* Xamarin.iOS: https://github.com/CartoDB/mobile-team/tree/master/projects/data.collection

**Comment by jaakla** [comment]
Created feature doc for more definitions and background info: https://docs.google.com/a/cartodb.com/document/d/1kIdpz8sMuFn8Kq9kCTDYEQaGTwoOdKeGtSXx8DaPYAI/edit?usp=sharing
